In [3]:
#1. 1. Import the numpy package under the name np 
import numpy as np

In [4]:
#2. 2. Print the numpy version and the configuration
np.__version__

'1.20.3'

In [8]:
np.__config__.show()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [29]:
#3.Create a null vector of size 10
n0 = np.zeros(10)
n0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
#4 How to find the memory size of any array
array = [1,1,1,1,1,1,1,1,1,1,1,1,1]
np.size(array)

13

In [18]:
#5 How to get the documentation of the numpy add function from the command line?
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x7fb19f887970>, toplevel='numpy')>

In [28]:
#6. Create a null vector of size 10 but the fifth value which is 1 Create a null vector of size 10 but the fifth value which is 1 
n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [35]:
#7. Create a vector with values ranging from 10 to 49
nn = np.arange(10,50)
nn

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [37]:
#8.Reverse a vector (first element becomes last)
nn[:: -1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [41]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
nrange = np.arange(9).reshape(3,3)
nrange

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] 
ind = [1,2,0,0,4,0] 
np.nonzero(ind)

(array([0, 1, 4]),)

In [47]:
#11. Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
#12. Create a 3x3x3 array with random values
np.random.random((3, 3, 3))

array([[[0.29825584, 0.11947115, 0.41556507],
        [0.13307799, 0.16062498, 0.3394581 ],
        [0.50044047, 0.39507251, 0.55762831]],

       [[0.61775888, 0.31747607, 0.61709298],
        [0.92206795, 0.51426694, 0.4494838 ],
        [0.04500274, 0.49261403, 0.03037018]],

       [[0.45170088, 0.08302583, 0.27037145],
        [0.88370114, 0.08819718, 0.16147207],
        [0.00848353, 0.18381849, 0.84415066]]])

In [71]:
#13  Create a 10x10 array with random values and find the minimum and maximum values
ran10 = np.random.random((10,10))
nmin, nmax  = np.min(ran10), np.max(ran10)
print(nmin, nmax)

0.005086813760229236 0.9958546379586933


In [79]:
#14 Create a random vector of size 30 and find the mean value
ranavg = np.random.random(30)
np.mean(ranavg)

0.41063082871669787

In [ ]:
#15 Create a 2d array with 1 on the border and 0 inside

In [ ]:
#16 How to add a border (filled with 0's) around an existing array?

In [ ]:
#17 What is the result of the following expression? 

In [ ]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
#19 Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [56]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#21 Create a checkerboard 8x8 matrix using the tile function

In [ ]:
#22 Normalize a 5x5 random matrix

In [ ]:
#23 Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [ ]:
#24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [ ]:
#25 Given a 1D array, negate all elements which are between 3 and 8, in place.